name: FFmpeg vvenc Parallel (1-100)

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        VIDEO_ID: [301]
    steps:
    # ----------------------------------------
    - name: Checkout repository
      uses: actions/checkout@v4

    # ----------------------------------------
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y unzip xz-utils megatools wget

    # ----------------------------------------
    - name: Download FFmpeg
      run: |
        mkdir -p ffmpeg_bin
        cd ffmpeg_bin
        wget https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz
        tar -xf ffmpeg-master-latest-linux64-gpl.tar.xz

    # ----------------------------------------
    - name: Set variables
      run: |
        echo "FFMPEG=ffmpeg_bin/ffmpeg-master-latest-linux64-gpl/bin/ffmpeg" >> $GITHUB_ENV
        echo "INPUT=dataset/${{ matrix.VIDEO_ID }}.mp4" >> $GITHUB_ENV

    # ----------------------------------------
    - name: Cache dataset
      uses: actions/cache@v4
      with:
        path: dataset
        key: dataset-mega-v1-${{ runner.os }}

    # ----------------------------------------
    - name: Download dataset
      run: |
        if [ ! -d dataset ]; then
          mkdir -p dataset_zip
          megadl "https://mega.nz/file/kIdhyATA#QjiOI1xFOZjRWpRUKSSPFRWzBx2WpUQ1PLfezxmt740" --path dataset_zip
          mkdir -p dataset
          unzip -o dataset_zip/*.zip -d dataset
        fi

    # ----------------------------------------
    - name: Convert MP4 → YUV (VVENC)
      run: |
        mkdir -p output

        echo "Processing $INPUT"

        $FFMPEG -y -i "$INPUT" \
        -c:v libvvenc \
        -qp 32 \
        -pix_fmt yuv420p \
        -an \
        output/${{ matrix.VIDEO_ID }}.mkv

    # ----------------------------------------
    - name: Upload output
      uses: actions/upload-artifact@v4
      with:
        name: yuv-${{ matrix.VIDEO_ID }}
        path: output/${{ matrix.VIDEO_ID }}.yuv
